FROM nvcr.io/nvidia/deepstream-l4t:6.3-samples

# Set working directory in the container
WORKDIR /app

# Install dependencies for RTSP Streaming on L4T ARM64 environment
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgstrtspserver-1.0-0 \
    libgstrtspserver-1.0-dev \
    gstreamer1.0-rtsp \
    build-essential \
    cmake \
    git \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Copy the entire project into /app in the container
COPY . /app/

# Run DeepStream with the config file in the config/ directory
CMD ["deepstream-app", "-c", "config/deepstream_app_config.txt"]